---
- name: Adding ips to the host list
  hosts: localhost
  gather_facts: no
  vars_files:
  - "{{ playbook_dir }}/vars/vm_details.yml"
  tasks:
    - name: Adding hosts to the list
      ansible.builtin.add_host:
        name: "{{ item.ip }}"
        group: target_hosts
      loop: "{{ vm_details }}"

    - debug: var=target_hosts

- name: pre checks before patching
  hosts: target_hosts
  gather_facts: true
  vars_files:
  - "{{ playbook_dir }}/vars/var.yml"
  - "{{ playbook_dir }}/vars/default.yml"
  tasks:
    - name: Disk space checking 
      ansible.builtin.import_role: 
        name: disk_space_checking

    - name: Checking application status
      ansible.builtin.import_role:
        name: app_check
         
    - name: monitoring tool status Check
      ansible.builtin.import_role:
        name: monitoring_tool

- name: Taking backup before OS patching
  hosts: localhost
  vars_files:
  - "{{ playbook_dir }}/vars/var.yml"  
  tasks:
    - name: Creating vms volume list
      ansible.builtin.import_role:
        name: volume_list
        
    - name: Backing up vms before applying patching
      ansible.builtin.import_role:
        name: vm_backup
        
- name: Applying patch to the vms
  hosts: target_hosts
  vars_files:
  - "{{ playbook_dir }}/vars/var.yml"
  - "{{ playbook_dir }}/vars/default.yml"
  tasks:        
    - name: patching vms after all pre-checks
      ansible.builtin.import_role: 
        name: update

# Application/DB smoke test need to write logic

- name: Reverting changes back if app/db not working as expected
  hosts: localhost
  tasks:
    - name: changing vms to old state
      ansible.builtin.import_role:
        name: failure_backup

# Questions to be asked
What is the down time for OS patching
How much they taken down time
What is the preferrable method for recovery ( backup/ snapshot)
Backup require cinder-backup is it available
How many vms they update simultaneously
print pdf after update all at a time 