role:
  linux_disk_space: false
  linux_registration: false
  linux_update: false
  win_update: false
  win_disk_space: false
  get_linux_packages_list: false
  get_win_packages_list: false


redhat:
  username: "fwieyfgikw"
  password: "weiugfi"