role:
  linux_disk_space: true
  linux_registration: false
  linux_update: false
  win_update: false
  win_disk_space: false
  get_linux_packages_list: true
  get_win_packages_list: false
  install_dp_linux: false
  install_dp_win: false

redhat:
  username: "fwieyfgikw"
  password: "weiugfi"
