- name: register a user
  community.general.redhat_subscription:
    state: present
    username: "{{ redhat.username }}"
    password: "{{ redhat.password }}"
    auto_attach: true
  when: linux_registration and {{ ansible_os_family }} == "Redhat"
