- name: creating images of vms
  ansible.builtin.shell: "openstack server image create --name {{ item.name }}-{{ ansible_date_time.iso8601 }} {{ item.name }}"
  loop: "{{ instance_snapshot }}"
  ignore_errors: true