- name: checking whether app is running
  ansible.builtin.shell: "if ps -eaf | egrep "apache|http|pmon|oracle"| grep -v grep >/dev/null; then echo "Process is running."; else echo "Process is not running."; fi" # Need to write code
  register: app_status_check

- name: Display application status
  ansible.builtin.debug:
    msg: "Application is in running state"
  when: app_status_check.stdout == "Process is running"
