---
# tasks file for roles/pdf
- name: Gathering packages list information
  import_tasks: linux_list.yml
  when: role.get_linux_packages_list

- name: Saving updateable packages data in PDF formatted file
  import_tasks: linux.yml
  when: role.get_linux_packages_list

- name: Gathering packages list information
  import_tasks: win_list.yml
  when: role.get_win_packages_list 

- name: Saving updateable packages data in PDF formatted file
  import_tasks: win.yml
  when: role.get_win_packages_list