- name: Get list of win updates
  ansible.windows.win_updates:
    category_names: 
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
    state: listed
  register: updateable_packages

