- name: Check free space on /
  ansible.builtin.set_fact:
    free_space_gb: "{{ (item.size_available | int / 1024 / 1024 / 1024) | round(2)}}"
  loop: "{{ ansible_mounts }}"
  when: item.mount == "/"

- name: Report free disk space
  ansible.builtin.debug:
    msg: "Available disk space on '/' : {{ free_space_gb }} GB"

- name: Fail if there is not enough space
  ansible.builtin.fail:
    msg: "Host localhost does not have enough disk space on /"
  when: "{{ free_space_gb }} < 20"